name: Workflow Dispatch Template
run-name: Running - ${{github.event_name}}
on: 
    workflow_dispatch:
        inputs: 
            serie: 
                description: Escreva algo!
                type: string
jobs: 
    on-workflow_dispatch: 
        runs-on: ubuntu-latest
        steps: 
          - name: Comentario
            run: | 
                echo "Comentário WORKFLOW DISPATCH"
                echo "Você escreveu: ${{inputs.serie}}" 