name: cron Job Template
run-name: Running - ${{github.event_name}}
on: 
    schedule:
        - cron: '30 5 * * 1,3' # 5:30 nas segundas e quartas
        - cron: '0 19 * * 2' # 19:00 nas terças
        - cron: '59 23 31 12 *'  # 23:59 no dia 31 de dezembro
        - cron: '30 11 11 12 *' 

jobs: 
    teste_schedule: 
        runs-on: ubuntu-latest
        steps:
          - run: echo "Já este passo sempre será executado"