name: Trigger
run-name: Running - Trigger
on: [push, workflow_dispatch]
jobs: 
    on-push:
        runs-on: ubuntu-latest
        steps: 

          - name: Coment√°rio
            run: echo trigger finalizado
            
          - name: Erro Proposital
            run: |
              echo "Provocando um erro intencional..."
              exit 1