name: Workflow run in_progress Template
run-name: Running - Workdflow run in_progress Template
on: 
    workflow_run: 
        workflows: [Trigger]
        types: [in_progress]

jobs: 
    quando_Trigger_for_disparado: 
        runs-on: ubuntu-latest
        steps: 
          - name: Coment√°rio
            run: echo "workflow run in_progress foi trigado." 